### ISSUE TITLE
SimpleSearch breaks website after server migration

### ISSUE THREAD

**Issue by Lovehelmet** [modxcms/SimpleSearch#54]
- MODx admin works as expected but no webpage renders, just get an error 500.
- Uninstalling SimpleSearch fixes the issue and everything works fine.
- Reinstalling SimpleSearch breaks the site again.

Now, I have a site developed locally that van't go live with a functional search.

**Comment by halftrainedharry** [comment]
What versions of MODX and SimpleSearch are you using? (There are at the moment 2 different versions of SimpleSearch for MODX 2.x and 3.x respectively.)
What's the PHP version? How does the webserver differ from you local setup?

Can you check the PHP error log to see what the exact error message is?

**Comment by Lovehelmet** [comment]
Hi,
I’m currently developing locally on two different MacBooks using:


  *   ModX 3.0.1
  *   MAMP 6.6
  *   Apache web server
  *   PHP 7.4.21
  *   MySQL 5.7.34
  *   SimpleSearch 3.0.0-alpha

The setup is the same on both MacBooks.
I migrate back and forth between these two MacBooks to keep all the sites up to date both at work and at home.

This has never been a problem until I implemented SimpleSearch, which technically, is the perfect search tool for the kind of sites I develop.

Now,
The websites I develop with SimpleSearch all works perfectly. It’s when I migrate from one computer to the other it stops working, and not just SimpleSearch but the whole website. In ModX Manager all works but the website shows, apart from error 500, nothing, no source code, no nothing.

If I uninstall SimpleSearch on this migrated website, everything works perfectly, apart for the search-function of course.
If I re-install SimpleSearch it all breaks again.

Simply put, I can only get SimpleSearch to work on the original website, not the migrated one, no matter on which of my to MacBooks I developed the website.

I’ve also tried un-installing SimpleSearch AND removing all packages, deleting all cached files and then re-installing SimpleSearch.
Same result unfortunately.

//Bosse

Bo Lovenhjelm
[signature_2087664032]
Frontend Developer
[signature_1918481955]
Direct: +46 433 27 30 38
NIBE AB NIBE Energy Systems
Switchboard: +46 433 27 30 00
nibe.se<https://www.nibe.se> | nibe.eu<https://www.nibe.eu> | nibe.com<https://www.nibe.com>

NIBE AB behandlar dina personuppgifter enligt: nibe.se/integritetspolicy<https://www.nibe.eu/sv-se/om-nibe/integritetspolicy>
NIBE AB process your personal information according to: nibe.eu/privacypolicy<https://nibe.eu/privacypolicy>


***@***.***
Sedan 1952 har NIBE tillverkat energieffektiva klimatiseringslösningar för hem och större fastigheter.
Allt startade i småländska Markaryd och idag är vi ett internationellt innovationsföretag som fyller 70 år.
Vi arbetar ständigt med att skapa nytta för våra kunder och bidrar till att allt fler kan leva mer hållbart.

Från: halftrainedharry ***@***.***>
Datum: tisdag, 11 oktober 2022 20:53
Till: modxcms/SimpleSearch ***@***.***>
Kopia: Bo Lovenhjelm ***@***.***>, Author ***@***.***>
Ämne: Re: [modxcms/SimpleSearch] SimpleSearch breaks website after server migration (Issue #54)
What versions of MODX and SimpleSearch are you using? (There are at the moment 2 different versions of SimpleSearch for MODX 2. x and 3. x respectively. ) What's the PHP version? How does the webserver differ from you local setup? Can you check
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

What versions of MODX and SimpleSearch are you using? (There are at the moment 2 different versions of SimpleSearch for MODX 2.x and 3.x respectively.)
What's the PHP version? How does the webserver differ from you local setup?

Can you check the PHP error log to see what the exact error message is?

**Comment by halftrainedharry** [comment]
Check the system setting "simplesearch.driver_class". Make sure the value is `\SimpleSearch\Driver\SimpleSearchDriverBasic`.

---

If this doesn't solve the problem then please check the **PHP error log**. An exact error message (where and why the error occurred) would help a lot to solve the issue.

If you are unsure where the PHP error log is located, take a look at the config file "php.ini". Probably the setting `error_log`.  (Maybe also check the values of other settings like `log_errors`, `display_errors`, `error_reporting`.)

**Comment by Lovehelmet** [comment]
Ok, I will.
Thanx for getting back to me and help so far. 😊
I’ll get back to you.

//Bosse

Bo Lovenhjelm
[signature_160495380]
Frontend Developer
[signature_2011416591]
Direct: +46 433 27 30 38
NIBE AB NIBE Energy Systems
Switchboard: +46 433 27 30 00
nibe.se<https://www.nibe.se> | nibe.eu<https://www.nibe.eu> | nibe.com<https://www.nibe.com>

NIBE AB behandlar dina personuppgifter enligt: nibe.se/integritetspolicy<https://www.nibe.eu/sv-se/om-nibe/integritetspolicy>
NIBE AB process your personal information according to: nibe.eu/privacypolicy<https://nibe.eu/privacypolicy>


***@***.***
Sedan 1952 har NIBE tillverkat energieffektiva klimatiseringslösningar för hem och större fastigheter.
Allt startade i småländska Markaryd och idag är vi ett internationellt innovationsföretag som fyller 70 år.
Vi arbetar ständigt med att skapa nytta för våra kunder och bidrar till att allt fler kan leva mer hållbart.

Från: halftrainedharry ***@***.***>
Datum: onsdag, 12 oktober 2022 09:56
Till: modxcms/SimpleSearch ***@***.***>
Kopia: Bo Lovenhjelm ***@***.***>, Author ***@***.***>
Ämne: Re: [modxcms/SimpleSearch] SimpleSearch breaks website after server migration (Issue #54)
Check the system setting "simplesearch. driver_class". Make sure the value is \SimpleSearch\Driver\SimpleSearchDriverBasic. If this doesn't solve the problem then please check the PHP error log. An exact error message (where and why the error
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Check the system setting "simplesearch.driver_class". Make sure the value is \SimpleSearch\Driver\SimpleSearchDriverBasic.

________________________________

If this doesn't solve the problem then please check the PHP error log. An exact error message (where and why the error occurred) would help a lot to solve the issue.

If you are unsure where the PHP error log is located, take a look at the config file "php.ini". Probably the setting error_log. (Maybe also check the values of other settings like log_errors, display_errors, error_reporting.)

**Comment by Lovehelmet** [comment]
Hi again,
I ended up with upgrading  MAMP with mySQL to latest version on both computers which resolved the initial problem.
However, now I have another issue..

SimpleSearch only returns hits if search is made from pages without subpages as seen in dump below.
If search is made when on a subpage SimpleSearch seems to search for a resource in the parent of that subpage and not the actual searchresults page (id 46) which is in the root.

Does SimpleSearch only work in sites that doesn't have subpages or is there a way to fix this?

Search made from page without subpage:
[cid:18b9c30c-28f8-4f33-a1c1-f6742af00893]

Search made from page with subpage:
[cid:75bf25e9-ae9b-4b94-a787-f1c35698b700]

Resource tree in manager:
[cid:be5b0e89-5ab0-4f73-a4a5-915465083c6d]
________________________________
Från: halftrainedharry ***@***.***>
Skickat: den 12 oktober 2022 09:56
Till: modxcms/SimpleSearch ***@***.***>
Kopia: Bo Lovenhjelm ***@***.***>; Author ***@***.***>
Ämne: Re: [modxcms/SimpleSearch] SimpleSearch breaks website after server migration (Issue #54)

Check the system setting "simplesearch. driver_class". Make sure the value is \SimpleSearch\Driver\SimpleSearchDriverBasic. If this doesn't solve the problem then please check the PHP error log. An exact error message (where and why the error
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Check the system setting "simplesearch.driver_class". Make sure the value is \SimpleSearch\Driver\SimpleSearchDriverBasic.

________________________________

If this doesn't solve the problem then please check the PHP error log. An exact error message (where and why the error occurred) would help a lot to solve the issue.

If you are unsure where the PHP error log is located, take a look at the config file "php.ini". Probably the setting error_log. (Maybe also check the values of other settings like log_errors, display_errors, error_reporting.)

**Comment by halftrainedharry** [comment]
I don't quite understand what your setup is.

Do you show the search form on every page ``[[!SimpleSearchForm? &landing=`46`]]`` and then on page 46 you display the search results `[[!SimpleSearch]]`?

SimpleSearch should always search the whole website (all resources) unless you define a property like `&ids` in your snippet call.

**Comment by Lovehelmet** [comment]
yes, thst is exactly right.
I have the search form included on every page via the menu and the results page is 46.

it only finds theresulys page with id 46 from pages that is not subpages. From a subpage it searches from subpage it just ads id 46 to the end of the url and doesn't render hits on the results page.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by halftrainedharry** [comment]
> it only finds theresulys page with id 46 from pages that is not subpages.

What is the value of the _action_ parameter in your form? This should be the same for every page and subpage.

`<form class="simplesearch-search-form" action="searchresultspage.html" method="get">`

What is the value of the action parameter in your template?

`<form class="simplesearch-search-form" action="[[~[[+landing]]]]" method="[[+method]]">`

**Comment by Lovehelmet** [comment]
Form action:
<form class="simplesearch-search-form" action="[[~[[+landing]]]]" method="[[+method]]">

Template:
 [[!SimpleSearchForm? &landing=`46`]]
________________________________
Från: halftrainedharry ***@***.***>
Skickat: den 13 oktober 2022 12:16
Till: modxcms/SimpleSearch ***@***.***>
Kopia: Bo Lovenhjelm ***@***.***>; Author ***@***.***>
Ämne: Re: [modxcms/SimpleSearch] SimpleSearch breaks website after server migration (Issue #54)

it only finds theresulys page with id 46 from pages that is not subpages. What is the value of the action parameter in your form? This should be the same for every page and subpage. <form class="simplesearch-search-form" action="searchresultspage. html"
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

it only finds theresulys page with id 46 from pages that is not subpages.

What is the value of the action parameter in your form? This should be the same for every page and subpage.

<form class="simplesearch-search-form" action="searchresultspage.html" method="get">

What is the value of the action parameter in your template?

<form class="simplesearch-search-form" action="[[~[[+landing]]]]" method="[[+method]]">

**Comment by halftrainedharry** [comment]
But what is the actual value that is shown in the source code for the _action_ attribute on your subpage?

What is the "Resource Alias" of your search-results-page? (On the screenshot this page seems to be unpublished. It should be published to be publicly accessible.)

The id parameter in the form `<input type="hidden" name="id" value="[[+landing]]" />` is irrelevant if friendly-urls are used (which seems to be the case).

**Comment by Lovehelmet** [comment]
The actual value in the source code for the action attribute on your subpage is 46.
The resource alias is: sökresultat - the same as the title.
It is published but hidden from menus.
So which id-parameter should be used for friendly urls?
________________________________
Från: halftrainedharry ***@***.***>
Skickat: den 13 oktober 2022 12:46
Till: modxcms/SimpleSearch ***@***.***>
Kopia: Bo Lovenhjelm ***@***.***>; Author ***@***.***>
Ämne: Re: [modxcms/SimpleSearch] SimpleSearch breaks website after server migration (Issue #54)

But what is the actual value that is shown in the source code for the action attribute on your subpage? What is the "Resource Alias" of your search-results-page? (On the screenshot this page seems to be unpublished. It should be published to
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

But what is the actual value that is shown in the source code for the action attribute on your subpage?

What is the "Resource Alias" of your search-results-page? (On the screenshot this page seems to be unpublished. It should be published to be publicly accessible.)

The id parameter in the form <input type="hidden" name="id" value="[[+landing]]" /> is irrelevant if friendly-urls are used (which seems to be the case).

**Comment by Lovehelmet** [comment]
And the rendered value in source code on every page when search is made is:

<form class="simplesearch-search-form" action="sökresultat/" method="get">

//Bosse

Bo Lovenhjelm
[signature_3209181915]
Frontend Developer
[signature_3514940998]
Direct: +46 433 27 30 38
NIBE AB NIBE Energy Systems
Switchboard: +46 433 27 30 00
nibe.se<https://www.nibe.se> | nibe.eu<https://www.nibe.eu> | nibe.com<https://www.nibe.com>

NIBE AB behandlar dina personuppgifter enligt: nibe.se/integritetspolicy<https://www.nibe.eu/sv-se/om-nibe/integritetspolicy>
NIBE AB process your personal information according to: nibe.eu/privacypolicy<https://nibe.eu/privacypolicy>


***@***.***
Sedan 1952 har NIBE tillverkat energieffektiva klimatiseringslösningar för hem och större fastigheter.
Allt startade i småländska Markaryd och idag är vi ett internationellt innovationsföretag som fyller 70 år.
Vi arbetar ständigt med att skapa nytta för våra kunder och bidrar till att allt fler kan leva mer hållbart.

Från: halftrainedharry ***@***.***>
Datum: torsdag, 13 oktober 2022 12:46
Till: modxcms/SimpleSearch ***@***.***>
Kopia: Bo Lovenhjelm ***@***.***>, Author ***@***.***>
Ämne: Re: [modxcms/SimpleSearch] SimpleSearch breaks website after server migration (Issue #54)
But what is the actual value that is shown in the source code for the action attribute on your subpage? What is the "Resource Alias" of your search-results-page? (On the screenshot this page seems to be unpublished. It should be published to
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

But what is the actual value that is shown in the source code for the action attribute on your subpage?

What is the "Resource Alias" of your search-results-page? (On the screenshot this page seems to be unpublished. It should be published to be publicly accessible.)

The id parameter in the form <input type="hidden" name="id" value="[[+landing]]" /> is irrelevant if friendly-urls are used (which seems to be the case).

**Comment by halftrainedharry** [comment]
> And the rendered value in source code on every page when search is made is: 
> `<form class="simplesearch-search-form" action="sökresultat/" method="get">`

So when you submit the search form, there is a html-request to `yourdomain.com/sökresultat/` on every page with a get parameter _search_ for the search value.

Why wouldn't this work on a subpage? Maybe the `<base>` tag is wrong on your subpage?

On your screenshot above ("4 results found ...") why is there no `sökresultat/` in the URL?

**Comment by halftrainedharry** [comment]
Something is wrong with your friendly URLs.

When you navigate in the manager to the "Sökresultat" resource and click the "View" button (in the top right corner), what is the URL? It should be `http://localhost/bootstrap/sokresultat` (or maybe `http://localhost/bootstrap/sokresultat.html`).

Now if you manually add a "search" parameter to the URL (`http://localhost/bootstrap/sokresultat?search=test`) you should see the search results. This is all the search form has to do. Navigate to the "Sökresultat" page and provide a search string.

If nothing else works, maybe try hard-coding the "Sökresultat" URL in the search form.

If the URL of the "Sökresultat" is wrong, check the database table  `modx_site_content` (columns "uri" and "alias") or try "Manage" -> "Clear Cache" -> "Refresh URIs".

---

> The URL shown in this case is: http://localhost/bootstrap/?search=bygg&id=46

This URL is wrong. It should be `http://localhost/bootstrap/sokresultat?search=bygg` (or `http://localhost/bootstrap/sokresultat?search=bygg&id=46`)

The fact that it works is more a coincidence. When friendly URLs are not enabled, the URL of a page is `http://localhost/bootstrap/index.php?id=46` (`http://localhost/bootstrap?id=46` also works because `index.php` is the default file).

When friendly URLs are enabled the id parameter is generally ignored (`?id=46`), but it is still possible to request a page per id ( `http://localhost/bootstrap/index.php?id=46`) unless the system setting `request_method_strict` is set to `Yes`.

But you can't call `http://localhost/bootstrap/om-oss/?id=46`. There exists no `index.php` file in an `om-oss` folder! `om-oss` is used to load the corresponding resource and `?id=46` is ignored.

**Comment by Lovehelmet** [comment]
When I navigate in the manager to the "Sökresultat" resource and click the "View" button (in the top right corner), the URL is http://localhost/bootstrap/sokresultat/
Yes, when I manually add the search string to above URL as: http://localhost/bootstrap/sokresultat/?search=bygg the “right” page renders the results as intended.

Can you give me an example of how hard coding the "Sökresultat" URL in the search form would look like in the form below?

<form class="simplesearch-search-form" action="[[~[[+landing]]]]" method="[[+method]]">
    <fieldset>
        <label for="[[+searchIndex]]">[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]</label>

        <input type="search" name="[[+searchIndex]]" id="[[+searchIndex]]" value="[[+searchValue]]" />
        <input type="hidden" name="id" value="[[+landing]]" />

        <input type="submit" value="[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]" />
    </fieldset>
</form>

//Bosse

Bo Lovenhjelm
[signature_813729974]
Frontend Developer
[signature_3335593295]
Direct: +46 433 27 30 38
NIBE AB NIBE Energy Systems
Switchboard: +46 433 27 30 00
nibe.se<https://www.nibe.se> | nibe.eu<https://www.nibe.eu> | nibe.com<https://www.nibe.com>

NIBE AB behandlar dina personuppgifter enligt: nibe.se/integritetspolicy<https://www.nibe.eu/sv-se/om-nibe/integritetspolicy>
NIBE AB process your personal information according to: nibe.eu/privacypolicy<https://nibe.eu/privacypolicy>


***@***.***
Sedan 1952 har NIBE tillverkat energieffektiva klimatiseringslösningar för hem och större fastigheter.
Allt startade i småländska Markaryd och idag är vi ett internationellt innovationsföretag som fyller 70 år.
Vi arbetar ständigt med att skapa nytta för våra kunder och bidrar till att allt fler kan leva mer hållbart.

Från: halftrainedharry ***@***.***>
Datum: måndag, 17 oktober 2022 10:01
Till: modxcms/SimpleSearch ***@***.***>
Kopia: Bo Lovenhjelm ***@***.***>, Author ***@***.***>
Ämne: Re: [modxcms/SimpleSearch] SimpleSearch breaks website after server migration (Issue #54)
Something is wrong with your friendly URLs. When you navigate in the manager to the "Sökresultat" resource and click the "View" button (in the top right corner), what is the URL? It should be http: //localhost/bootstrap/sokresultat [localhost]
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Something is wrong with your friendly URLs.

When you navigate in the manager to the "Sökresultat" resource and click the "View" button (in the top right corner), what is the URL? It should be http://localhost/bootstrap/sokresultat [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/sokresultat__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-U_cy6Rn$> (or maybe http://localhost/bootstrap/sokresultat.html [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/sokresultat.html__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-QmsKuLG$>).

Now if you manually add a "search" parameter to the URL (http://localhost/bootstrap/sokresultat?search=test [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/sokresultat?search=test__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-Yi3eXnl$>) you should see the search results. This is all the search form has to do. Navigate to the "Sökresultat" page and provide a search string.

If nothing else works, maybe try hard-coding the "Sökresultat" URL in the search form.

If the URL of the "Sökresultat" is wrong, check the database table modx_site_content (columns "uri" and "alias") or try "Manage" -> "Clear Cache" -> "Refresh URIs".

________________________________

The URL shown in this case is: http://localhost/bootstrap/?search=bygg&id=46 [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/?search=bygg&id=46__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-aaNxL54$>

This URL is wrong. It should be http://localhost/bootstrap/sokresultat?search=bygg [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/sokresultat?search=bygg__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-Qrm6FJE$> (or http://localhost/bootstrap/sokresultat?search=bygg&id=46 [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/sokresultat?search=bygg&id=46__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-RSLdpeg$>)

The fact that it works is more a coincidence. When friendly URLs are not enabled, the URL of a page is http://localhost/bootstrap/index.php?id=46 [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/index.php?id=46__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-duv9ZGi$> (http://localhost/bootstrap?id=46 [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap?id=46__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-QR24lRu$> also works because index.php is the default file).

When friendly URLs are enabled the id parameter is generally ignored (?id=46), but it is still possible to request a page per id ( http://localhost/bootstrap/index.php?id=46 [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/index.php?id=46__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-duv9ZGi$>) unless the system setting request_method_strict is set to Yes.

But you can't call http://localhost/bootstrap/om-oss/?id=46 [localhost]<https://urldefense.com/v3/__http:/localhost/bootstrap/om-oss/?id=46__;!!HMLeYTom!Bza9DgkwvAWxvD8cI0COz_6KFe4A8QnbgTN3NSOUkTTYMQcEvTPP8xNMO2dMNmaz_um5WJCeG-kdyvMJth7K-fV8a66s$>. There exists no index.php file in an om-oss folder! om-oss is used to load the corresponding resource and ?id=46 is ignored.

**Comment by halftrainedharry** [comment]
> Can you give me an example of how hard coding the "Sökresultat" URL in the search form would look like in the form below?

Just add the URL to the action attribute
`<form class="simplesearch-search-form" action="http://localhost/bootstrap/sokresultat/" method="[[+method]]">` 

Or maybe this works as well:
``<form class="simplesearch-search-form" action="[[~[[+landing]]? &scheme=`full`]]" method="[[+method]]">``
(Using a different URL scheme: https://docs.modx.com/3.x/en/building-sites/settings/link_tag_scheme)

**Comment by Lovehelmet** [comment]
Tried both:
```
<form class="simplesearch-search-form" action="http://localhost/bootstrap/sokresultat/" method="[[+method]]">
    <fieldset>
        <label for="[[+searchIndex]]">[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]</label>
        <input type="search" name="[[+searchIndex]]" id="[[+searchIndex]]" value="[[+searchValue]]" />
        <input type="hidden" name="id" value="[[+landing]]" />
        <input type="submit" value="[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]" />
    </fieldset>
</form>
```

And:
```
<form class="simplesearch-search-form" action="[[~[[+landing]]? &scheme=`full`]]" method="[[+method]]">
    <fieldset>
        <label for="[[+searchIndex]]">[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]</label>
        <input type="search" name="[[+searchIndex]]" id="[[+searchIndex]]" value="[[+searchValue]]" />
        <input type="hidden" name="id" value="[[+landing]]" />
        <input type="submit" value="[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]" />

    </fieldset>
</form>
```

Makes no difference at all so same disapointing results as before, only on start page and if I make a search from the results page rendered from search made on start page  works...

Else is: http://localhost/bootstrap/byggtjanster/snickeri/?search=bygg&id=46 as an example.

**Comment by Lovehelmet** [comment]
Both adding the form manually to a page and adding the link-tag works.
http://localhost/bootstrap/sokresultat/?search=bygg

As you can see the code is also in the "SearchForm" chunk, but that affects nothing.
Seames like nothing I change in this chunk affects the results..

![Skärmavbild 2022-10-17 kl  11 39 52](https://user-images.githubusercontent.com/89969167/196145230-3461c5a8-b8c0-4cc0-848d-2c1a94578159.png)

**Comment by halftrainedharry** [comment]
Duplicate the chunk, give it another name (e.g. "mySearchForm")and then add a `&tpl` property to the snippet call.
```
[[!SimpleSearchForm? &landing=`46` &tpl=`mySearchForm`]]
```

**Comment by Lovehelmet** [comment]
Did that and tried 3 different ways in new chunk:
```
<form class="simplesearch-search-form" action="[[~[[+landing]]]]" method="[[+method]]">
    <fieldset>
        <label for="[[+searchIndex]]">[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]</label>

        <input type="search" name="[[+searchIndex]]" id="[[+searchIndex]]" value="[[+searchValue]]" />
        <input type="hidden" name="id" value="[[+landing]]" />

        <input type="submit" value="[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]" />
 
    </fieldset>
</form>
```

```
<form class="simplesearch-search-form" action="http://localhost/bootstrap/sokresultat/" method="get">
    <fieldset>
        <label for="[[+searchIndex]]">[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]</label>

        <input type="search" name="[[+searchIndex]]" id="[[+searchIndex]]" value="[[+searchValue]]" />
        <input type="hidden" name="id" value="[[+landing]]" />

        <input type="submit" value="[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]" />
 
    </fieldset>
</form>
```

```
<form class="simplesearch-search-form" action="[[~[[+landing]]? &scheme=`full`]]" method="[[+method]]">
    <fieldset>
        <label for="[[+searchIndex]]">[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]</label>

        <input type="search" name="[[+searchIndex]]" id="[[+searchIndex]]" value="[[+searchValue]]" />
        <input type="hidden" name="id" value="[[+landing]]" />

        <input type="submit" value="[[%simplesearch.search? &namespace=`simplesearch` &topic=`default`]]" />
 
    </fieldset>
</form>
```
So when I either search from the index ro add the tag-link or your search form directly to a page it renders results and URL is: http://localhost/bootstrap/sokresultat/?search=bygg

When I make a search from any other page there is no results and the URL is: http://localhost/bootstrap/om-oss/?search=bygg&id=46


![Skärmavbild 2022-10-17 kl  12 00 15](https://user-images.githubusercontent.com/89969167/196149432-1409f4a1-845b-42fc-a382-1b9e4ccb2718.png)
![Skärmavbild 2022-10-17 kl  12 00 39](https://user-images.githubusercontent.com/89969167/196149433-4985410b-1c13-4dd8-a828-7bcb4da7f2cf.png)

**Comment by Lovehelmet** [comment]
The output from "mySearchForm" when using standard setup is:
```
<form class="simplesearch-search-form" action="sokresultat/" method="get">
  <fieldset>
   <label for="search">Sök</label>  
   <input type="search" name="search" id="search" value="bygg" />
   <input type="hidden" name="id" value="46" />  
   <input type="submit" value="Sök" />  
   </fieldset>
 </form>
```

When using alternativ 2 the output is:
```
<form class="simplesearch-search-form" action="http://localhost/bootstrap/sokresultat/" method="get">
    <fieldset>
        <label for="search">Sök</label>
        <input type="search" name="search" id="search" value="bygg" />
        <input type="hidden" name="id" value="46" />
        <input type="submit" value="Sök" />
    </fieldset>
</form>
```
When using alternativ 3 the output is:
```
<form class="simplesearch-search-form" action="http://localhost/bootstrap/sokresultat/" method="get">
    <fieldset>
        <label for="search">Sök</label>

        <input type="search" name="search" id="search" value="bygg" />
        <input type="hidden" name="id" value="46" />

        <input type="submit" value="Sök" />
 
    </fieldset>
</form>

```

Tried deleting the line:
`<input type="hidden" name="id" value="[[+landing]]" />`
No change

When replacing standard form in mySearchForm chunk with:
```
<form class="simplesearch-search-form" action="http://localhost/bootstrap/sokresultat/" method="get">
    <fieldset>
        <input type="search" name="search" id="search" value="" />
        <input type="submit" value="Search" />
    </fieldset>
</form>
```
Nothing happens, though it works when inserted directly on the page.

So, for example I've put both the form and the tag-link directly on a certain page and the search results page shows.
When making the search from the form linked in via the menu on the same page it does not.

**Comment by halftrainedharry** [comment]
Is there any Javascript code on your page that may interfere?
Maybe some code that rewrites links in the menu and by accident also changes the search form?

**Comment by Lovehelmet** [comment]
Well, there are som scripts but none of them rewrites links in any way.
Also I can't see any difference between linked in form in menu and search code inserted directly on the page as both forms renders when page loads and therefore are actually on the rendered page before search is made in both cases.

I'm really mindf**d by this issue as I really can't figure out a working solution and delivery of webpage is delayed.. :(
But like I said before, I can mail a link to a migration folder to you so you can download, set it up and see for yourself if you want.

**Comment by halftrainedharry** [comment]
> But like I said before, I can mail a link to a migration folder to you so you can download, set it up and see for yourself if you want.

No, I don't want that.
In my opinion this is a frontend issue. So if you have a publicly accessible version of the site I can take a look at it.

---

And maybe (temporarily) disable javascript in the browser, just to make sure that no javascript code interferes.

**Comment by Lovehelmet** [comment]
I've "solved" the matter by removing the search form from linked in modal in main menu and creating a search page with the form directly on that page. Not as elegant but it works.
Thanks for trying to help and sorry for wasting your time.
Regards,
//Bo
